FROM python:3.6
# Or any preferred Python version.
COPY ../* .

WORKDIR ./ner-evaluation

RUN pip install -r requirements.txt

RUN ls

# CMD [“python”, “./main.py”] 
# Or enter the name of your unique directory and parameter set.
